Repository IF-103-Java/ims, pull requests merged in 2019-12, with the labels that each got.

#24 Added GlobalExceptionHandler
  src/main/java/com/ita/if103java/ims/config/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/exception/BaseRuntimeException.java
  src/main/java/com/ita/if103java/ims/exception/CRUDException.java
  src/main/java/com/ita/if103java/ims/exception/EntityNotFoundException.java
  src/main/java/com/ita/if103java/ims/exception/UserNotFoundException.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: enhancement

#28 Add JDBCTemplate beans
  src/main/java/com/ita/if103java/ims/ImsApplication.java
  src/main/java/com/ita/if103java/ims/config/JDBCTemplateConfig.java
Labels: enhancement

#25 Add Addresses DAO
  pom.xml
  src/main/java/com/ita/if103java/ims/dao/impl/AddressDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AddressDaoImpl.java
  src/main/java/com/ita/if103java/ims/entity/Address.java
  src/main/java/com/ita/if103java/ims/exception/AddressNotFoundException.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AddressRowMapper.java
Labels: dao

#33 Fix AddressDao package location
  src/main/java/com/ita/if103java/ims/dao/AddressDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AddressDaoImpl.java
Labels: hotfix

#26 User controller
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: controller, dao

#34 Add AbstractEntityDtoMapper
  src/main/java/com/ita/if103java/ims/mapper/AbstractEntityDtoMapper.java
Labels: enhancement

#29 Implemented AssociateDto, AssociateService, some fixes
  src/main/java/com/ita/if103java/ims/dao/AssociateDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AssociateDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/AddressDto.java
  src/main/java/com/ita/if103java/ims/dto/AssociateDto.java
  src/main/java/com/ita/if103java/ims/mapper/AddressDtoMapper.java
  src/main/java/com/ita/if103java/ims/mapper/AssociateDtoMapper.java
  src/main/java/com/ita/if103java/ims/service/AssociateService.java
  src/main/java/com/ita/if103java/ims/service/impl/AssociateServiceImpl.java
Labels: service

#31 Hotfix JDBC Template queries with enum
  src/main/java/com/ita/if103java/ims/dao/impl/TransactionDaoImpl.java
Labels: bug, hotfix

#41 Add --enable-preview flag when run jar
  .gitignore
  Dockerfile
Labels: devops, hotfix

#42 Enhance UserDtoMapper
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/mapper/UserDtoMapper.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: dtoMapper, enhancement

#36 Warehouse management
  pom.xml
  src/main/java/com/ita/if103java/ims/dao/WarehouseDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/WarehouseDto.java
  src/main/java/com/ita/if103java/ims/exception/CRUDException.java
  src/main/java/com/ita/if103java/ims/exception/EntityNotFoundException.java
  src/main/java/com/ita/if103java/ims/exception/WarehouseNotFoundException.java
  src/main/java/com/ita/if103java/ims/mapper/WarehouseDtoMapper.java
  src/main/java/com/ita/if103java/ims/service/WarehouseService.java
  src/main/java/com/ita/if103java/ims/service/impl/WarehouseServiceImpl.java
Labels: service

#47 LoginController&LoginService
  pom.xml
  src/main/java/com/ita/if103java/ims/config/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/config/MailMessagesConfig.java
  src/main/java/com/ita/if103java/ims/config/PasswordEncoderConfig.java
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserLoginDto.java
  src/main/java/com/ita/if103java/ims/exception/UserOrPasswordIncorrectException.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenProvider.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/LoginService.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/MailServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/java/com/ita/if103java/ims/util/TokenUtil.java
  src/main/resources/application.properties
Labels: configuration, controller, enhancement, service

#55 Rearrange entries and add multiline string
  src/main/java/com/ita/if103java/ims/config/MailMessagesConfig.java
  src/main/java/com/ita/if103java/ims/controller/DashboardController.java
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
  src/main/java/com/ita/if103java/ims/dao/DashboardDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountTypeDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AssociateDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/DashboardDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/ItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/SavedItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/entity/Account.java
  src/main/java/com/ita/if103java/ims/entity/Event.java
  src/main/java/com/ita/if103java/ims/entity/EventName.java
  src/main/java/com/ita/if103java/ims/exception/BaseRuntimeException.java
  src/main/java/com/ita/if103java/ims/exception/EntityNotFoundException.java
  src/main/java/com/ita/if103java/ims/exception/MaxWarehouseDepthLimitReachedException.java
  src/main/java/com/ita/if103java/ims/exception/MaxWarehousesLimitReachedException.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AccountRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AccountTypeRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AddressRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/ChargeCapacityRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/WarehouseLoadRowMapper.java
  src/main/java/com/ita/if103java/ims/service/DashboardService.java
  src/main/java/com/ita/if103java/ims/service/impl/AssociateServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/DashboardServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/test/java/com/ita/if103java/ims/ImsApplicationTests.java
Labels: enhancement

#57 Distribute exceptionHandler and enhance userDto
  src/main/java/com/ita/if103java/ims/config/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/mapper/UserDtoMapper.java
  src/main/resources/application.properties
Labels: hotfix

#69 Websocket
  src/main/java/com/ita/if103java/ims/config/WebSocketConfig.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/entity/Event.java
Labels: hotfix

#67 add pagination
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: enhancement

#71 add spring security
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/exception/security/InvalidJwtTokenException.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AccountRowMapper.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenFilter.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenFilterConfigurer.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenProvider.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
Labels: spring-security

#70 add errorInfoDto
  src/main/java/com/ita/if103java/ims/config/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/dto/PesponseWrapperDto.java
Labels: enhancement

#80 Add dynamic destination for notifications
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
Labels: hotfix, service
