Repository IF-103-Java/ims, pull requests merged in 2020-01, with the labels that each got.

#68 Add events for user actions
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/java/com/ita/if103java/ims/util/UserEventUtil.java
Labels: enhancement, service

#81 Add changes according to requirements
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/dto/WarehouseToAssociateDistanceDto.java
  src/main/java/com/ita/if103java/ims/mapper/UserDtoMapper.java
  src/main/java/com/ita/if103java/ims/service/AccountService.java
  src/main/java/com/ita/if103java/ims/service/impl/AccountServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/InvitationServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: enhancement, hotfix

#84 User role
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/entity/Role.java
  src/main/java/com/ita/if103java/ims/mapper/UserDtoMapper.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/InvitationServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: hotfix

#78 Update Jenkinsfile
  Jenkinsfile
Labels: devops, enhancement

#76 Add finding best suppliers, clients
  src/main/java/com/ita/if103java/ims/dao/BestTradeDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/BestTradeDaoImpl.java
  src/main/java/com/ita/if103java/ims/entity/TotalTransactionQuantity.java
Labels: dao

#87 Returns Page<Event>, fixed eventDTO, warehouseRowMapper , added AbstractRowMapper
  src/main/java/com/ita/if103java/ims/dao/EventDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/EventDto.java
  src/main/java/com/ita/if103java/ims/mapper/EventDtoMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/EventRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/WarehouseRowMapper.java
  src/main/java/com/ita/if103java/ims/service/EventService.java
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
  src/main/java/com/ita/if103java/ims/util/RowMapperUtil.java
Labels: controller, dao, service

#91 EventController returns Page
  src/main/java/com/ita/if103java/ims/controller/EventController.java
Labels: hotfix

#90 Fix plugin duplication
  pom.xml
Labels: hotfix

#93 Add BestTradeService with DTO
  src/main/java/com/ita/if103java/ims/dto/BestTradeDto.java
  src/main/java/com/ita/if103java/ims/service/BestTradeService.java
  src/main/java/com/ita/if103java/ims/service/impl/BestTradeServiceImpl.java
Labels: service

#88 Enhance ExceptionHandler response DTO
  src/main/java/com/ita/if103java/ims/config/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/dto/PesponseWrapperDto.java
  src/main/java/com/ita/if103java/ims/dto/handler/ResponseMessageDto.java
Labels: enhancement

#100 Events
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/EventController.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/entity/EventName.java
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
Labels: bug, hotfix

#101 Event hotfix
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/EventController.java
Labels: hotfix

#99 add cors to controllers
  src/main/java/com/ita/if103java/ims/controller/AccountController.java
  src/main/java/com/ita/if103java/ims/controller/AssociateController.java
  src/main/java/com/ita/if103java/ims/controller/DashboardController.java
  src/main/java/com/ita/if103java/ims/controller/EventController.java
  src/main/java/com/ita/if103java/ims/controller/InvitationController.java
  src/main/java/com/ita/if103java/ims/controller/ItemController.java
  src/main/java/com/ita/if103java/ims/controller/SavedItemController.java
  src/main/java/com/ita/if103java/ims/controller/TransactionController.java
  src/main/java/com/ita/if103java/ims/controller/UpgradeController.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
Labels: configuration

#103 Events populateInfo
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/WarehouseDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
Labels: dao, service

#105 Fix --enable-preview for spring-boot maven plugin
  pom.xml
Labels: hotfix

#104 Add TopWarehouseDao
  src/main/java/com/ita/if103java/ims/dao/TopWarehouseDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/TopWarehouseDaoImpl.java
Labels: dao

#96 Add AddressLinkerDao
  src/main/java/com/ita/if103java/ims/dao/AddressLinkerDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AddressLinkerDaoImpl.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/AssociateAddressRowMapper.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/WarehouseAddressRowMapper.java
Labels: dao

#106 fix token return
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/service/LoginService.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
Labels: hotfix

#108 Add cors configuration
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/config/WebConfig.java
  src/main/java/com/ita/if103java/ims/controller/AccountController.java
  src/main/java/com/ita/if103java/ims/controller/AssociateController.java
  src/main/java/com/ita/if103java/ims/controller/DashboardController.java
  src/main/java/com/ita/if103java/ims/controller/EventController.java
  src/main/java/com/ita/if103java/ims/controller/InvitationController.java
  src/main/java/com/ita/if103java/ims/controller/ItemController.java
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/SavedItemController.java
  src/main/java/com/ita/if103java/ims/controller/TransactionController.java
  src/main/java/com/ita/if103java/ims/controller/UpgradeController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
Labels: configuration

#114 Added endpoints to User, Warehouse, Event Controllers
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/controller/EventController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/entity/EventName.java
  src/main/java/com/ita/if103java/ims/entity/EventType.java
  src/main/java/com/ita/if103java/ims/service/EventService.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/WarehouseService.java
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/WarehouseServiceImpl.java
Labels: controller, dao, service

#119 Add ignoring UserDetailsImpl parameter in SwaggerConfig
  src/main/java/com/ita/if103java/ims/config/SwaggerConfig.java
Labels: configuration

#123 Add @Transactional, fix registration
  src/main/java/com/ita/if103java/ims/controller/AccountController.java
  src/main/java/com/ita/if103java/ims/controller/AssociateController.java
  src/main/java/com/ita/if103java/ims/controller/DashboardController.java
  src/main/java/com/ita/if103java/ims/controller/InvitationController.java
  src/main/java/com/ita/if103java/ims/controller/ItemController.java
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/SavedItemController.java
  src/main/java/com/ita/if103java/ims/controller/TransactionController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountTypeDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/AccountServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UpgradeSimpleServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: hotfix, service

#120 Adviser/controller
  src/main/java/com/ita/if103java/ims/controller/WarehouseAdviceController.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
Labels: controller

#125 Events Hotfix
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
Labels: dao, hotfix

#130 Fix app.properties
  src/main/java/com/ita/if103java/ims/config/MailConfig.java
  src/main/resources/application.properties
Labels: hotfix

#134 Fix security
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenFilter.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenProvider.java
Labels: spring-security

#133 fix pagination for warehouses
  src/main/java/com/ita/if103java/ims/annotation/ApiPageable.java
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/WarehouseService.java
  src/main/java/com/ita/if103java/ims/service/impl/WarehouseServiceImpl.java
Labels: service

#141 ApiPegaeble
  src/main/java/com/ita/if103java/ims/controller/EventController.java
Labels: hotfix

#135 Fix update method, combine with update account
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: hotfix, service

#139 Add ability to sort
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
Labels: enhancement

#149 UserDao and WarehouseDao fix
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/EventServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: bug, hotfix

#155 Add resetPasswordDto and return username from login method
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/ForgotPasswordDto.java
  src/main/java/com/ita/if103java/ims/service/LoginService.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
Labels: hotfix

#157 set findAll return type Page<>
  src/main/java/com/ita/if103java/ims/controller/WarehouseController.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/WarehouseService.java
  src/main/java/com/ita/if103java/ims/service/impl/WarehouseServiceImpl.java
Labels: hotfix
