Repository IF-103-Java/ims, pull requests merged in 2020-02, with the labels that each got.

#166 Fix/security
  src/main/java/com/ita/if103java/ims/security/JwtTokenFilter.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenProvider.java
Labels: hotfix

#174 Delete useless in controller and secure some endpoints
  src/main/java/com/ita/if103java/ims/config/SecurityConfig.java
  src/main/java/com/ita/if103java/ims/config/WebConfig.java
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/mapper/jdbc/UserRowMapper.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenFilterConfigurer.java
  src/main/java/com/ita/if103java/ims/security/JwtTokenProvider.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: hotfix

#194 Check number of users during activation. Specify return type in a sin…
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/service/LoginService.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/InvitationServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/main/java/com/ita/if103java/ims/util/TokenUtil.java
Labels: enhancement

#195 Add hard delete
  src/main/java/com/ita/if103java/ims/dao/AddressDao.java
  src/main/java/com/ita/if103java/ims/dao/AssociateDao.java
  src/main/java/com/ita/if103java/ims/dao/ItemDao.java
  src/main/java/com/ita/if103java/ims/dao/SavedItemDao.java
  src/main/java/com/ita/if103java/ims/dao/TransactionDao.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/WarehouseDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AddressDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AssociateDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/ItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/SavedItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/TransactionDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: service

#196 Enhance update-password method
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/ResetPasswordDto.java
  src/main/java/com/ita/if103java/ims/handler/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/service/UserService.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
Labels: enhancement

#199 Test/user
  src/main/java/com/ita/if103java/ims/config/GeneratedKeyHolderFactory.java
  src/main/java/com/ita/if103java/ims/config/KeyHolderFactory.java
  src/main/java/com/ita/if103java/ims/dao/impl/AccountDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/AddressDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/EventDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/ItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/SavedItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/TransactionDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/WarehouseDaoImpl.java
  src/main/java/com/ita/if103java/ims/util/JDBCUtils.java
  src/test/java/com/ita/if103java/ims/dao/UserDaoImplTest.java
Labels: tests

#205 Add services tests
  src/main/java/com/ita/if103java/ims/dao/ItemDao.java
  src/main/java/com/ita/if103java/ims/dao/UserDao.java
  src/main/java/com/ita/if103java/ims/dao/impl/ItemDaoImpl.java
  src/main/java/com/ita/if103java/ims/dao/impl/UserDaoImpl.java
  src/main/java/com/ita/if103java/ims/dto/AccountDto.java
  src/main/java/com/ita/if103java/ims/dto/ResetPasswordDto.java
  src/main/java/com/ita/if103java/ims/dto/UserDto.java
  src/main/java/com/ita/if103java/ims/entity/User.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/UserServiceImpl.java
  src/test/java/com/ita/if103java/ims/DataUtil.java
  src/test/java/com/ita/if103java/ims/dao/UserDaoImplTest.java
  src/test/java/com/ita/if103java/ims/service/LoginServiceImplTest.java
  src/test/java/com/ita/if103java/ims/service/MailServiceImplTest.java
  src/test/java/com/ita/if103java/ims/service/UserServiceImplTest.java
Labels: tests

#208 Add controller tests
  src/main/java/com/ita/if103java/ims/controller/LoginController.java
  src/main/java/com/ita/if103java/ims/controller/RegistrationController.java
  src/main/java/com/ita/if103java/ims/controller/UserController.java
  src/main/java/com/ita/if103java/ims/handler/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/security/UserDetailsImpl.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/test/java/com/ita/if103java/ims/controller/EventControllerTest.java
  src/test/java/com/ita/if103java/ims/controller/UserControllerTest.java
  src/test/java/com/ita/if103java/ims/dao/UserDaoImplTest.java
  src/test/java/com/ita/if103java/ims/security/SecurityInterceptor.java
  src/test/java/com/ita/if103java/ims/service/LoginServiceImplTest.java
  src/test/java/com/ita/if103java/ims/service/MailServiceImplTest.java
  src/test/java/com/ita/if103java/ims/service/UserServiceImplTest.java
  src/test/java/com/ita/if103java/ims/util/DataUtil.java
Labels: tests

#211 Account controllers tests + some dao exceptions tests.
  src/test/java/com/ita/if103java/ims/controller/AccountControllerTest.java
  src/test/java/com/ita/if103java/ims/controller/InvitationControllerTest.java
  src/test/java/com/ita/if103java/ims/controller/UpgradeControllerTest.java
  src/test/java/com/ita/if103java/ims/dao/AccountTypeDaoImplTest.java
Labels: tests

#212 Add controller tests
  src/main/java/com/ita/if103java/ims/dto/ForgotPasswordDto.java
  src/main/java/com/ita/if103java/ims/dto/UserLoginDto.java
  src/main/java/com/ita/if103java/ims/handler/GlobalExceptionHandler.java
  src/main/java/com/ita/if103java/ims/service/impl/LoginServiceImpl.java
  src/test/java/com/ita/if103java/ims/IgnoreJacksonWriteOnlyAccess.java
  src/test/java/com/ita/if103java/ims/controller/LoginControllerTest.java
  src/test/java/com/ita/if103java/ims/controller/RegistrationControllerTest.java
  src/test/java/com/ita/if103java/ims/controller/UserControllerTest.java
  src/test/java/com/ita/if103java/ims/dao/UserDaoImplTest.java
Labels: near_the_finish_line, tests
